### ISSUE TITLE
Non-existent class in migrations

### ISSUE THREAD

**Issue by viktorprogger** [tecnocen-com/yii2-oauth2-server#7]
## **What steps will reproduce the problem?**
Try to run migrations.

## **What is the expected result?**
Migrations are ok.

## **What do you get instead?**

```
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'tecnocen\migrate\CreateTableMigration' not found'
```

**Comment by viktorprogger** [comment]
There are [two places](https://github.com/tecnocen-com/yii2-oauth2-server/search?q=CreateTableMigration&unscoped_q=CreateTableMigration) where this class is used. And there is no implementation.

**Comment by koma136** [comment]
> There are [two places](https://github.com/tecnocen-com/yii2-oauth2-server/search?q=CreateTableMigration&unscoped_q=CreateTableMigration) where this class is used. And there is no implementation.

https://github.com/tecnocen-com/yii2-migrate

**Comment by viktorprogger** [comment]
What do you mean?
